---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: safe
    autoremove: true

- name: Install git-core
  apt:
    pkg: git-core
    state: present
    update_cache: true
  become: yes

- name: Install Vim
  apt:
    pkg: vim
    state: present
    update_cache: true
  become: yes

- name: Create app directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ mnt_dir }}/database"
    - "{{ mnt_dir }}/redis"
    - "{{ mnt_dir }}/media"
    - "{{ mnt_dir }}/certs"
    - "{{ mnt_dir }}/custom_templates"
    - "{{ mnt_dir }}/caddy"
    - "{{ mnt_dir }}/caddy/data"
    - "{{ mnt_dir }}/caddy/config"

- name: Copy Caddyfile
  ansible.builtin.template:
    src: Caddyfile
    dest: "{{ mnt_dir }}/caddy/Caddyfile"
    owner: "{{ansible_ssh_user}}"
    group: "{{ansible_ssh_user}}"
    mode: u=rw,g=r,o=
